### PR TITLE
Add --glsl-version option and fix #397 (for declaration in GLSL 100 es)

### LINKED ISSUE #397: Opt out of "Merge for-declaration with the previous declaration"
Would it be possible to have a way to opt out of the change introduced in #371?

The form `int a=2, b=3; for (; ...)` is not valid in GLSL ES, and hence not valid in WebGL 1.

See Appendix A of the spec [here](https://www.khronos.org/files/opengles_shading_language.pdf), specifically these lines:

> - The for statement has the form:
>     - for ( _init-declaration_ ; _condition_ ; _expression_ ) _statement_
> - init-declaration has the form:
>     - _type-specifier_ identifier = constant-expression
>
> Consequently the loop variable cannot be a global variable.

### PR DESCRIPTION
**Pull request by therontarigo**

### CODE REVIEW

**Comment by laurentlb** [comment]
Do you think we could read the version from the `#version` line? Or it won't be sufficient?

**Comment by therontarigo** [comment]
That would be good too, but cmdline should be kept as an override as there are various reasons the `#version` line may not exist in the source: a project may be putting it in after minification, or as a separate string, or in some cases it is not needed - WebGL1 defaults to `100 es` (I think) and OpenGL defaults to `110 compatibility`.

**Comment by laurentlb** [comment]
That makes sense. We could consider a single flag `--lang`  to switch between HLSL, GLSL, GLSL ES.

**Comment by therontarigo** [comment]
Perhaps, though I simply followed `glslang` convention here:
```
  --glsl-version {100 | 110 | 120 | 130 | 140 | 150 |
                300es | 310es | 320es | 330
                400 | 410 | 420 | 430 | 440 | 450 | 460}
                                    set GLSL version, overrides #version
                                    in shader sourcen
```
`glslang` also uses a single flag for switching to HLSL.

**Comment by eldritchconundrum** [comment]
Having a command line flag is also good for reusing the same test file in different versions.

What should happen when #version exists and does not match the command line flag? Use #version, use command-line, show a warning or show an error?

Eventually expressions like `(options.hlsl || options.glslver>0 || options.esslver>=300)` should probably be moved to a method with a name describing the feature being tested, in some kind of Version object.

**Comment by therontarigo** [comment]
> #version exists and does not match the command line flag

Override the interpretation (as `glslang` does) and show a warning (and leave the literal `#version` line untouched).

`(options.hlsl || options.glslver>0 || options.esslver>=300)` could be simplified as `not (options.esslver>0 && options.esslver<300)`.

Something like this?
```
module LangFeature
let dynamicloops = not (options.esslver>0 && options.esslver<300)
```

**Comment by therontarigo** [comment]
The `implicitconv` language feature flag is because of this WIP: https://github.com/therontarigo/Shader_Minifier/compare/glslversion...therontarigo:Shader_Minifier:constants

**Comment by therontarigo** [comment]
"100es" does not exist in `glslang`, and `#version 100 es` is not valid in any environment - confusing as it is, the real behavior of OpenGL is that `#version N` (with no "es") selects ESSL when N=100, and OpenGL GLSL otherwise.  Likewise in `glslang` the ESSL version options are named `100 | 300es | 310es | 320es`.  Closing for now.

**Pull request closed without merging**
